image: ruby:3.2

stages:
  - deploy

variables:
  BUNDLE_PATH: "vendor/bundle"
  JEKYLL_ENV: "production"
  GITHUB_REPO_SLUG: "grab/engineering-blog"

cache:
  paths:
    - vendor/bundle

.bundle_install:
  before_script:
    - gem install bundler -v 2.7.2
    - bundle config set path "$BUNDLE_PATH"
    - bundle install --frozen

jekyll_build:
  extends: .bundle_install
  stage: deploy
  script:
    - bundle exec jekyll build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy_github:
  extends: .bundle_install
  stage: deploy
  before_script:
    - gem install bundler -v 2.7.2
    - bundle config set path "$BUNDLE_PATH"
    - bundle install --frozen
    - git config --global user.email "gitlab-ci@users.noreply.gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - bundle exec jekyll build
    - JEKYLL_ENV=production bundle exec jgd -u "https://$GH_TOKEN@github.com/$GITHUB_REPO_SLUG.git"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
