image: ruby:3.0

stages:
  - deploy

variables:
  BUNDLE_PATH: "vendor/bundle"
  JEKYLL_ENV: "production"
  GITHUB_REPO_SLUG: "grab/engineering-blog"

cache:
  paths:
    - vendor/bundle

deploy_github:
  stage: deploy
  before_script:
    - gem install bundler -v 2.4.22
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
    - git config --global user.email "gitlab-ci@users.noreply.gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - bundle exec jekyll build
    - JEKYLL_ENV=production bundle exec jgd -u "https://$GH_TOKEN@github.com/$GITHUB_REPO_SLUG.git"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
